### ISSUE TITLE
update

### ISSUE THREAD

**Issue by mojtabas74** [felixduvallet/deep-time-reading#1]
Hi, can you update the code ? many of function change in tensor flow. i update some of code but when i run training i got this error
TypeError: Fetch argument <function merge_all at 0x000001569E09D6A8> has invalid type <class 'function'>, must be a string or Tensor. (Can not convert a function into a Tensor or Operation.)

**Comment by felixduvallet** [comment]
I'm not actively maintaining or supporting this repository. However, I'd be happy to look at any pull request if you make progress towards updating the code.

**Comment by mojtabas74** [comment]
ok, just a question , which version of tensorflow,python,matplotlib do you use for this project?
