### ISSUE TITLE
The code generates 720 images all set to 12:00. 

### ISSUE THREAD

**Issue by Japkeerat** [felixduvallet/deep-time-reading#3]
Needs updating

**Comment by felixduvallet** [comment]
I'm not actively maintaining or supporting this repository. However, I'd be happy to look at any pull request if you make progress towards updating the code.

**Comment by Japkeerat** [comment]
Sure thing. I'll look into the required changes once I am over with my current project. This project was awesome. So let's not let it rot here.

**Comment by agodatt** [comment]
Replacing this line: map(lambda bt: bt[0].set_x(bt[1]), zip(bars, rads))
with this solves the issue:
    for i in range(3):
        bars[i].set_x(rads[i])
